### ISSUE TITLE
clf.clusters，this is created without resolve

### ISSUE THREAD

**Issue by ShouriYang** [jforjohn/canopyKmeans_improved#1]
in MyCanopy.py
line 262
clf.clusters is created without resolve

**Comment by jforjohn** [comment]
This is a work in progress for the paper mentioned in the README.
The code contains still some comments that need to be removed like the one in line 262.
However, the algorithm doesn't seem to perform like the one in the paper...

**Comment by ShouriYang** [comment]
So it means that the code is not completed?------------------ 原始邮件 ------------------
发件人: "Ysot"<notifications@github.com>
发送时间: 2019年6月10日(星期一) 凌晨1:16
收件人: "jforjohn/canopyKmeans_improved"<canopyKmeans_improved@noreply.github.com>;
抄送: "ShouriYang"<451044764@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jforjohn/canopyKmeans_improved] clf.clusters，this is created without resolve (#1)



This is a work in progress for the paper mentioned in the README.
 The code contains still some comments that need to be removed like the one in line 262.
 However, the algorithm doesn't seem to perform like the one in the paper...
 
&mdash;

**Comment by jforjohn** [comment]
No, it's not completed.
