### ISSUE TITLE
FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks. ---

### ISSUE THREAD

**Issue by zuihu** [jforjohn/canopyKmeans_improved#2]
Hi,may I ask what these warnings are and what impact they have?I've just come into contact with the k-means algorithm,What do these ERR, ARI, Rep, JC, AMI, TB, BD, SC mean,thanks!
![image](https://user-images.githubusercontent.com/50262031/107230774-6fc95b00-6a5a-11eb-9d84-d11c26ed6aa4.png)

**Comment by jforjohn** [comment]
Hello,

the ERR is the same error metric as the one from the sklearn (the one used was the sum of squared distances). 
REP is the number of repetitions needed.
The rest are the abbreviations of external and internal validation metrics. Check Validation.py to see which ones were used.

**Comment by jforjohn** [comment]
Concerning the warning it's what it says. The sklearn version used in the code and the one you have are different. Currently the results should not be affected.

**Comment by zuihu** [comment]
Thank you very much for your answer. The canopy algorithm can give the best K value, so I still need to k-Means.cfg Number of K values specified in the?  Are those MyCanopyKmeans, MyKmeans++, StandCanopyKmeans, and so on, are the new eight algorithms resulting from the optimization of canopy and K-means algorithms?

**Comment by zuihu** [comment]
And do you need to use k-means algorithm to calculate the anchors?Because I only see the number of K values.

**Comment by zuihu** [comment]
And do you need to use k-means algorithm to calculate the anchors size?  Because I only see the number of K values are calculated

**Comment by jforjohn** [comment]
This is code compares the algorithms mentioned in the readme. The kmeans which uses the canopy as initialization doesn't need the k from the config file. This k is used for the rest of the algorithms. 
So, canopy can be applied as initialization for the rest of the algorithms (either their custom implementation or from any other package) but this is not implemented in this code, however, it doesn't need so many adjustments.
I don't get what you mean by anchors size here.

**Comment by zuihu** [comment]
Thanks. The mean of anchors size is in the YOLOv3 9 anchors(10*13, 16*30, 33*23,etc), how can I get these candidate boxes by my datasets?

**Comment by zuihu** [comment]
If my data set is large enough to cause memory error, how can I modify the code? (because there is no problem with my Python version, I only have 16g of memory, and I can't run it in colab)
![image](https://user-images.githubusercontent.com/50262031/107877941-66346d00-6f0a-11eb-80ba-4cb1e90ef411.png)

**Comment by jforjohn** [comment]
well, Canopy needs a distance matrix. At first try it in a much smaller dataset to see how it works. Then you need maybe to calculate the distance matrix separately. Try to do it in a small script in your machine otherwise try it in another machine and read it from Canopy code instead of calculating it. With 16GB you can store in memory up to ~1300x1300 matrix or ~2600x2600 with int32. 
I think if you don't have the distance matrix it will make the algorithm much slower but this is something you need to experiment with and check the paper it was derived from again.

**Comment by zuihu** [comment]
ok,thanks
